import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../src/Components/Footer";
import "./globals.css";
import Navbar from "@/src/Components/HomeComponents/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* <Navbar /> */}

          <Navbar/>
        </div>

        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
